services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lightningmcfilm
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mcfilm-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  user_service:
    build: ./backend/user_service
    container_name: user_service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@mysql_db:3306/lightningmcfilm
      - JWT_SECRET=2004320Lightning
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRES_MINUTES=10080
    volumes:
      - ./backend/user_service/uploads:/app/uploads
    networks:
      - mcfilm-net

  movie-service:
    build: ./backend/movies-service
    container_name: movie_service
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://imadominguez_db_user:88851974Asi@lightningmcfilm.7rescnu.mongodb.net/lightning-mcfilm?retryWrites=true&w=majority
      - OMDB_API_KEY=a40e9c2f
    networks:
      - mcfilm-net

  gateway:
    build: ./api-gateway
    container_name: api_gateway
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - user_service
      - movie-service
    networks:
      - mcfilm-net

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - mcfilm-net

networks:
  mcfilm-net:
    driver: bridge

volumes:
  mysql_data: